### ISSUE TITLE
Need bullet list (UL)

### ISSUE THREAD

**Issue by iannorway** [everpress-co/mailster-block-forms#7]
Hi!
The text block formatting options in a template (Letterbox etc.) include a numbered list (OL). We need a bulleted list option (UL) too. See enclosed screen shot. This seems to be something that has to be incorporated "behind the scenes" in Mailster and is not part of the individual template code.
![numbered list](https://user-images.githubusercontent.com/91468959/200160891-39f72d22-9c96-4824-bb77-4213a3aed430.jpg)

**Comment by evrpress** [comment]
Hey There,

Thank you for writing in! We provide all of our official support via the member area on our website. If you have not done so yet, please use the link below to register for access so that you can post your question there: https://mailster.co/go/register/

We are looking forward helping you out.
